/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasigudang;

import aplikasigudang.model.Transaksi;
import aplikasigudang.model.TransaksiDAO;
import com.lowagie.text.Element;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaulttblReport;
import javax.swing.text.Document;

/**
 *
 * @author ACER A314
 */
public class LaporanFrame extends javax.swing.JFrame {
    private TransaksiDAO transaksiDAO;

    /**
     * Creates new form LaporanFrame
     */
    public LaporanFrame() {
        initComponents();
        try {
        transaksiDAO = new TransaksiDAO(); // Inisialisasi DAO
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }    
    }

private void loadLaporanToTable(List<Transaksi> laporan) {
    DefaulttblReport model = (DefaulttblReport) tblReport.getModel();
    model.setRowCount(0); // Bersihkan tabel
    for (Transaksi transaksi : laporan) {
        model.addRow(new Object[]{
            transaksi.getIdTransaksi(),
            transaksi.getJenisTransaksi(),
            transaksi.getKodeBarang(),
            transaksi.getJumlah(),
            transaksi.getTanggal()
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnExportExcel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dcTanggalAwal = new com.toedter.calendar.JDateChooser();
        dcTanggalAkhir = new com.toedter.calendar.JDateChooser();
        btnReport = new javax.swing.JButton();
        btnExportPDF = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReport = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("My Thrift Store");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jLabel1)
                .addContainerGap(332, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        jLabel2.setText("Tanggal Awal");

        jLabel3.setText("Tanggal Akhir");

        btnReport.setBackground(new java.awt.Color(153, 153, 153));
        btnReport.setText("Report");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnExportPDF.setBackground(new java.awt.Color(153, 153, 153));
        btnExportPDF.setText("Cetak PDF");
        btnExportPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportPDFActionPerformed(evt);
            }
        });

        btnExcel.setBackground(new java.awt.Color(153, 153, 153));
        btnExcel.setText("Cetak Excel");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnExportExcelLayout = new javax.swing.GroupLayout(btnExportExcel);
        btnExportExcel.setLayout(btnExportExcelLayout);
        btnExportExcelLayout.setHorizontalGroup(
            btnExportExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExportExcelLayout.createSequentialGroup()
                .addGroup(btnExportExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnExportExcelLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(btnExportExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExportPDF)
                            .addComponent(btnReport)
                            .addComponent(btnExcel)))
                    .addGroup(btnExportExcelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(btnExportExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(btnExportExcelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addComponent(dcTanggalAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(btnExportExcelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(dcTanggalAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        btnExportExcelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnExcel, btnExportPDF, btnReport});

        btnExportExcelLayout.setVerticalGroup(
            btnExportExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExportExcelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(btnExportExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dcTanggalAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(22, 22, 22)
                .addGroup(btnExportExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(dcTanggalAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnReport)
                .addGap(18, 18, 18)
                .addComponent(btnExportPDF)
                .addGap(26, 26, 26)
                .addComponent(btnExcel)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        tblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Jenis", "Kode Barang", "Jumlah", "Tanggal"
            }
        ));
        jScrollPane1.setViewportView(tblReport);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnExportExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExportExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
    try {
        if (dcTanggalAwal.getDate() == null || dcTanggalAkhir.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Tanggal Awal dan Akhir tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Date tanggalAwal = dcTanggalAwal.getDate();
        Date tanggalAkhir = dcTanggalAkhir.getDate();

        List<Transaksi> laporan = transaksiDAO.getLaporan(tanggalAwal, tanggalAkhir);
        loadLaporanToTable(laporan);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }    // TODO add your handling code here:
    }//GEN-LAST:event_btnReportActionPerformed

private void saveToPDF() {
    // Nama file PDF yang akan disimpan
    String fileName = new Date().getTime() + "_Report.pdf";

    try {
        // Membuat objek Document untuk PDF dengan ukuran halaman A4
        com.lowagie.text.Document document = new com.lowagie.text.Document(PageSize.A4);

        // Menghubungkan dokumen dengan FileOutputStream menggunakan PdfWriter
        PdfWriter.getInstance(document, new FileOutputStream(fileName));

        // Membuka dokumen untuk penulisan
        document.open();

        // Menambahkan judul ke PDF dengan font tebal dan ukuran 16
        com.lowagie.text.Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16);
        com.lowagie.text.Paragraph title = new com.lowagie.text.Paragraph("Laporan Data Thrift", titleFont);
        title.setAlignment(Element.ALIGN_CENTER); // Mengatur judul rata tengah
        document.add(title);

        // Menambahkan spasi sebelum tabel
        document.add(new com.lowagie.text.Paragraph(" "));
        document.add(new com.lowagie.text.Paragraph(" ")); // Spasi tambahan

        // Membuat tabel dengan jumlah kolom sesuai dengan tabel
        int columnCount = tblReport.getColumnCount();
        com.lowagie.text.pdf.PdfPTable table = new com.lowagie.text.pdf.PdfPTable(columnCount);
        table.setWidthPercentage(100); // Mengatur lebar tabel agar memenuhi halaman

        // Menambahkan header ke tabel
        for (int i = 0; i < columnCount; i++) {
            com.lowagie.text.pdf.PdfPCell headerCell = new com.lowagie.text.pdf.PdfPCell(new com.lowagie.text.Phrase(tblReport.getColumnName(i)));
            headerCell.setHorizontalAlignment(Element.ALIGN_CENTER); // Rata tengah untuk header
            headerCell.setVerticalAlignment(Element.ALIGN_MIDDLE);  // Rata tengah vertikal
            table.addCell(headerCell); // Menambahkan header ke tabel
        }

        // Menambahkan data dari `tblReport` ke tabel PDF
        for (int i = 0; i < tblReport.getRowCount(); i++) { // Iterasi baris
            for (int j = 0; j < columnCount; j++) { // Iterasi kolom
                Object cellValue = tblReport.getValueAt(i, j);
                com.lowagie.text.pdf.PdfPCell dataCell = new com.lowagie.text.pdf.PdfPCell(new com.lowagie.text.Phrase(cellValue == null ? "" : cellValue.toString()));
                dataCell.setHorizontalAlignment(Element.ALIGN_CENTER); // Rata tengah untuk data
                dataCell.setVerticalAlignment(Element.ALIGN_MIDDLE);  // Rata tengah vertikal
                table.addCell(dataCell); // Menambahkan data ke tabel
            }
        }

        // Menambahkan tabel ke dokumen PDF
        document.add(table);

        // Menutup dokumen setelah selesai
        document.close();

        // Menampilkan pesan sukses
        JOptionPane.showMessageDialog(this, "Laporan berhasil disimpan ke " + fileName, "Sukses", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e) {
        // Menampilkan pesan error jika terjadi masalah saat menyimpan data
        JOptionPane.showMessageDialog(this, "Error menyimpan laporan ke PDF: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    
    private void btnExportPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportPDFActionPerformed
        saveToPDF();// TODO add your handling code here:
    }//GEN-LAST:event_btnExportPDFActionPerformed

private void saveToCSV() {
    // Get the current date to append to the file name (optional)
    String fileName = new Date().getTime()+"Report.csv";
    
    try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileName))) {
        // Write the header row
        writer.write("ID Transaksi, Jenis Transaksi, Kode Barang , Jumlah, Tanggal");
        writer.newLine();

        // Write data from the table
        for (int i = 0; i < tblReport.getRowCount(); i++) {
            StringBuilder row = new StringBuilder();
            for (int j = 0; j < tblReport.getColumnCount(); j++) {
                // Append each cell value followed by a comma, except for the last one
                row.append(tblReport.getValueAt(i, j));
                if (j < tblReport.getColumnCount() - 1) {
                    row.append(",");
                }
            }
            writer.write(row.toString());
            writer.newLine();
        }
        JOptionPane.showMessageDialog(this, "Data saved to " + fileName);
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error saving data to CSV: " + e.getMessage());
    }
}    
    
    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        saveToCSV();   // TODO add your handling code here:
    }//GEN-LAST:event_btnExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcel;
    private javax.swing.JPanel btnExportExcel;
    private javax.swing.JButton btnExportPDF;
    private javax.swing.JButton btnReport;
    private com.toedter.calendar.JDateChooser dcTanggalAkhir;
    private com.toedter.calendar.JDateChooser dcTanggalAwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReport;
    // End of variables declaration//GEN-END:variables
}
